CLASSES:
  lung: 255
  heart: 85
  body: 170
  background: 0

MODEL:
  TYPE: "model1"  # Options: model1, model2
  model1:  # Options: DeepLabV3Plus, SegFormer, Mask2Former
    ARCHITECTURE: "DeepLabV3Plus"
    ENCODER: "efficientnet-b0"
    ENCODER_WEIGHTS: "imagenet"
  model2:
    ARCHITECTURE: "unet"
    ENCODER: "mobilenet_v2"
    ENCODER_WEIGHTS: "imagenet"

FIGURE:
  SIZE: [512, 512]

TRAIN:
  BATCH_SIZE: 8
  LR: 0.0001
  EPOCHS: 500

SAVE_RESULTS:
  LOG: "logs/model1"
  MODEL: "models/model1"

SEED: 42
