MODEL:
  TYPE: "SegFormer"  # Options: DeepLabV3Plus, SegFormer, Mask2Former
  DeepLabV3Plus:
    ENCODER: "efficientnet-b0"
    ENCODER_WEIGHTS: "imagenet"
    CLASSES: ["lung"]
  SegFormer:
    NAME: "nvidia/segformer-b0-finetuned-ade-512-512"
    CLASSES: ["lung"]
  Mask2Former:
    NAME: "facebook/mask2former-swin-small-ade-semantic"
    CLASSES: ["lung"]

FIGURE:
  SIZE: [512, 512]

TRAIN:
  BATCH_SIZE: 8
  LR: 0.0001
  EPOCHS: 100

DEVICE: "cuda"
